[bumpver]
current_version = "1.2.3"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} → {new_version}"
tag_message = "release {new_version}"
tag_name = "v{new_version}"
commit = true
push = true

[bumpver.regex_patterns]
"pyproject.toml" = [
    'version\s*=\s*"{current_version}"',
]

